lint:
  files_unchanged:
    - .markdownlint.yml
    - assets/email_template.html
    - assets/email_template.txt
    - lib/NfcoreTemplate.groovy
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - lib/NfcoreSchema.groovy
