# General parameters
outdir : 'results'

max_memory : '60.GB'
max_cpus : 16

# Fetchngs parameters
input : 'data/ids.txt'

# Rnaseq parameters
# fasta : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/genome.fa'
# gtf : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/genes.gtf.gz'
# gff : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/genes.gff.gz'
# transcript_fasta : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/transcriptome.fasta'
# additional_fasta : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/gfp.fa.gz'

# bbsplit_fasta_list : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/bbsplit_fasta_list.txt'
# hisat2_index : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/hisat2.tar.gz'
# star_index : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/star.tar.gz'
# salmon_indeX : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/salmon.tar.gz'
# rsem_index : 'https://github.com/nf-core/test-datasets/raw/rnaseq/reference/rsem.tar.gz'

# skip_bbsplit : false
# pseudo_aligner : 'salmon'
# umitools_bc_pattern : 'NNNN'

# Viralrecon parameters
