contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #fetchngs channel"
    url: https://nfcore.slack.com/channels/fetchngs
    about: Discussion about the nf-core/fetchngs pipeline
